import { Politician } from '@/lib/types';

export const politicians: Politician[] = [
  {
    id: 1,
    name: 'Taro Yamada',
    party: 'Reform Party',
    age: 49,
    gender: 'Male',
    district: 'Tokyo-3',
    house: 'representatives',
    score: 91.6,
    previousRank: 3,
    topQuestion: 'Government AI procurement transparency hearing',
    keyAchievement: 'Led cross-party digital administration reform bill',
    summary: 'High floor performance with strong policy execution and committee influence.',
    metrics: { activity: 94, questionQuality: 87, legislation: 92, influence: 89, impact: 90 }
  },
  {
    id: 2,
    name: 'Keiko Tanaka',
    party: 'Civic Front',
    age: 42,
    gender: 'Female',
    district: 'Osaka-2',
    house: 'representatives',
    score: 89.9,
    previousRank: 1,
    topQuestion: 'Emergency childcare budget accountability',
    keyAchievement: 'Negotiated bipartisan maternal health support amendment',
    summary: 'Elite question quality and public-impact framing keep her at the top tier.',
    metrics: { activity: 90, questionQuality: 94, legislation: 86, influence: 88, impact: 91 }
  },
  {
    id: 3,
    name: 'Hiroshi Sato',
    party: 'Green Alliance',
    age: 55,
    gender: 'Male',
    district: 'Kanagawa',
    house: 'councillors',
    score: 88.4,
    previousRank: 5,
    topQuestion: 'Coastal resilience funding gap challenge',
    keyAchievement: 'Passed regional adaptation investment package',
    summary: 'Strong momentum from impactful legislation and climate committee leverage.',
    metrics: { activity: 83, questionQuality: 85, legislation: 92, influence: 86, impact: 94 }
  },
  {
    id: 4,
    name: 'Mina Kobayashi',
    party: 'Future Liberal',
    age: 37,
    gender: 'Female',
    district: 'Aichi-1',
    house: 'representatives',
    score: 86.5,
    previousRank: 4,
    topQuestion: 'STEM talent drain in local prefectures',
    keyAchievement: 'Secured scholarship expansion for technical colleges',
    summary: 'Fast-rising communicator with compelling quality-question profile.',
    metrics: { activity: 88, questionQuality: 90, legislation: 82, influence: 80, impact: 87 }
  },
  {
    id: 5,
    name: 'Daichi Nakamura',
    party: 'National Unity',
    age: 61,
    gender: 'Male',
    district: 'Hokkaido-5',
    house: 'representatives',
    score: 84.1,
    previousRank: 2,
    topQuestion: 'Fuel subsidy effectiveness review',
    keyAchievement: 'Authored winter logistics resilience framework',
    summary: 'Dropped after weak question quality despite high procedural activity.',
    metrics: { activity: 91, questionQuality: 72, legislation: 85, influence: 88, impact: 83 }
  },
  {
    id: 6,
    name: 'Yui Shimizu',
    party: 'Civic Front',
    age: 33,
    gender: 'Female',
    district: 'Fukuoka',
    house: 'councillors',
    score: 82.9,
    previousRank: 9,
    topQuestion: 'Housing affordability emergency motion',
    keyAchievement: 'Built youth housing consensus amendment',
    summary: 'Massive rise powered by quality interventions and social media traction.',
    metrics: { activity: 79, questionQuality: 91, legislation: 78, influence: 74, impact: 86 }
  },
  {
    id: 7,
    name: 'Riku Hayashi',
    party: 'Reform Party',
    age: 46,
    gender: 'Male',
    district: 'Chiba-4',
    house: 'representatives',
    score: 80.4,
    previousRank: 6,
    topQuestion: 'Defense procurement cost overruns',
    keyAchievement: 'Introduced procurement transparency dashboard mandate',
    summary: 'Solid influence score but needs stronger policy conversion velocity.',
    metrics: { activity: 84, questionQuality: 78, legislation: 80, influence: 83, impact: 77 }
  },
  {
    id: 8,
    name: 'Aoi Fujita',
    party: 'Green Alliance',
    age: 29,
    gender: 'Female',
    district: 'Kyoto-2',
    house: 'representatives',
    score: 78.8,
    previousRank: 10,
    topQuestion: 'Food waste reduction implementation gaps',
    keyAchievement: 'Won committee support for circular economy pilot',
    summary: 'Emerging voice with breakout question-quality upside.',
    metrics: { activity: 75, questionQuality: 88, legislation: 74, influence: 70, impact: 81 }
  },
  {
    id: 9,
    name: 'Shin Ito',
    party: 'National Unity',
    age: 58,
    gender: 'Male',
    district: 'Niigata',
    house: 'councillors',
    score: 76.2,
    previousRank: 7,
    topQuestion: 'Rural clinic closure escalation',
    keyAchievement: 'Secured emergency clinic bridge funding',
    summary: 'Strong regional impact but lower national influence metrics this cycle.',
    metrics: { activity: 81, questionQuality: 73, legislation: 76, influence: 69, impact: 82 }
  },
  {
    id: 10,
    name: 'Nao Okada',
    party: 'Future Liberal',
    age: 40,
    gender: 'Female',
    district: 'Saitama-6',
    house: 'representatives',
    score: 75.4,
    previousRank: 8,
    topQuestion: 'SME bankruptcy early-warning mechanisms',
    keyAchievement: 'Introduced SME cashflow stabilization package',
    summary: 'Reliable legislative contributor, but influence score is still developing.',
    metrics: { activity: 77, questionQuality: 76, legislation: 82, influence: 68, impact: 74 }
  }
];
