import { Politician } from '@/lib/types';

export const politicians: Politician[] = [
  {
    id: 1,
    name: '山田 太郎',
    party: '改革党',
    age: 49,
    gender: 'Male',
    district: '東京3区',
    house: 'representatives',
    score: 91.6,
    previousRank: 3,
    topQuestion: '政府AIの調達透明性に関する公聴会',
    keyAchievement: '超党派デジタル行政改革法案を主導',
    summary: '高い実績水準と強い政策実行力・委員会影響力を誇る。',
    metrics: { activity: 94, questionQuality: 87, legislation: 92, influence: 89, impact: 90 },
    isInactive: false
  },
  {
    id: 2,
    name: '田中 恵子',
    party: '市民前線',
    age: 42,
    gender: 'Female',
    district: '大阪2区',
    house: 'representatives',
    score: 89.9,
    previousRank: 1,
    topQuestion: '緊急保育予算の説明責任',
    keyAchievement: '超党派による母子保健支援法改正を交渉',
    summary: '高い質問品質と社会的インパクトにより、常にトップクラスを維持。',
    metrics: { activity: 90, questionQuality: 94, legislation: 86, influence: 88, impact: 91 },
    isInactive: false
  },
  {
    id: 3,
    name: '佐藤 博',
    party: '緑の連合',
    age: 55,
    gender: 'Male',
    district: '神奈川区',
    house: 'councillors',
    score: 88.4,
    previousRank: 5,
    topQuestion: '沿岸防災資金の不足問題への挑戦',
    keyAchievement: '地域適応投資パッケージを可決',
    summary: '影響力ある立法と気候委員会での活動による強い勢い。',
    metrics: { activity: 83, questionQuality: 85, legislation: 92, influence: 86, impact: 94 },
    isInactive: false
  },
  {
    id: 4,
    name: '小林 美奈',
    party: '未来自由党',
    age: 37,
    gender: 'Female',
    district: '愛知1区',
    house: 'representatives',
    score: 86.5,
    previousRank: 4,
    topQuestion: '地方県でのSTEM人材流出問題',
    keyAchievement: '専門学校向け奨学金拡充を実現',
    summary: '説得力ある質問実績を持つ急成長するコミュニケーター。',
    metrics: { activity: 88, questionQuality: 90, legislation: 82, influence: 80, impact: 87 },
    isInactive: false
  },
  {
    id: 5,
    name: '中村 大地',
    party: '国民統一党',
    age: 61,
    gender: 'Male',
    district: '北海道5区',
    house: 'representatives',
    score: 84.1,
    previousRank: 2,
    topQuestion: '燃料補助金の効果検証',
    keyAchievement: '冬季物流強靭化フレームワークを起草',
    summary: '高い手続き活動量に対して質問品質が低く、ランクを落とした。',
    metrics: { activity: 91, questionQuality: 72, legislation: 85, influence: 88, impact: 83 },
    isInactive: false
  },
  {
    id: 6,
    name: '清水 結衣',
    party: '市民前線',
    age: 33,
    gender: 'Female',
    district: '福岡区',
    house: 'councillors',
    score: 82.9,
    previousRank: 9,
    topQuestion: '住宅費緊急動議',
    keyAchievement: '若者向け住宅合意形成改正案を構築',
    summary: '質の高い介入とSNSの注目で大幅な上昇。',
    metrics: { activity: 79, questionQuality: 91, legislation: 78, influence: 74, impact: 86 },
    isInactive: false
  },
  {
    id: 7,
    name: '林 陸',
    party: '改革党',
    age: 46,
    gender: 'Male',
    district: '千葉4区',
    house: 'representatives',
    score: 80.4,
    previousRank: 6,
    topQuestion: '防衛調達コスト超過問題',
    keyAchievement: '調達透明性ダッシュボード義務化を導入',
    summary: '影響力スコアは高いが、政策実現速度の向上が課題。',
    metrics: { activity: 84, questionQuality: 78, legislation: 80, influence: 83, impact: 77 },
    isInactive: false
  },
  {
    id: 8,
    name: '藤田 葵',
    party: '緑の連合',
    age: 29,
    gender: 'Female',
    district: '京都2区',
    house: 'representatives',
    score: 78.8,
    previousRank: 10,
    topQuestion: '食品廃棄物削減の実施不足問題',
    keyAchievement: '循環型経済パイロット事業への委員会支持を獲得',
    summary: '質問品質で急浮上する新進気鋭の声。',
    metrics: { activity: 75, questionQuality: 88, legislation: 74, influence: 70, impact: 81 },
    isInactive: false
  },
  {
    id: 9,
    name: '伊藤 真',
    party: '国民統一党',
    age: 58,
    gender: 'Male',
    district: '新潟区',
    house: 'councillors',
    score: 76.2,
    previousRank: 7,
    topQuestion: '地方診療所閉鎖の深刻化',
    keyAchievement: '緊急診療所存続資金を確保',
    summary: '地域への影響は強いが、今期は全国的な影響力指標が低下。',
    metrics: { activity: 81, questionQuality: 73, legislation: 76, influence: 69, impact: 82 },
    isInactive: false
  },
  {
    id: 10,
    name: '岡田 奈緒',
    party: '未来自由党',
    age: 40,
    gender: 'Female',
    district: '埼玉6区',
    house: 'representatives',
    score: 75.4,
    previousRank: 8,
    topQuestion: '中小企業倒産早期警告メカニズム',
    keyAchievement: '中小企業キャッシュフロー安定化パッケージを導入',
    summary: '安定した立法貢献者だが、影響力スコアはまだ発展途上。',
    metrics: { activity: 77, questionQuality: 76, legislation: 82, influence: 68, impact: 74 },
    isInactive: false
  }
];
